version: '3'
services:
    website:
        image: quiooo/dominik-schwaiger.ch
        container_name: dominik-schwaiger.ch
        ports:
            - '3002:3000'
    website-dev:
        build:
            context: .
            dockerfile: dev.Dockerfile
        container_name: dominik-schwaiger.ch-dev
        volumes:
            - ./:/dominik-schwaiger.ch
        ports:
            - '3003:3000'