version: '3'
services:
    website:
        image: quiooo/dominik-schwaiger.ch
        container_name: dominik-schwaiger.ch
        ports:
            - '3002:3000'
        restart: always
        labels:
            - 'com.centurylinklabs.watchtower.enable=true'
        environment:
            - SCHWAIGER_ADMIN_PASSWORD=admin
