version: "3.9"
services:
  website:
    image: quiooo/dominik-schwaiger.ch
    ports:
      - "3000:3000"
    restart: always

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: quiooo/dominik-schwaiger.ch
