version: '3'
services:
  website:
    image: quiooo/dominik-schwaiger.ch
    ports:
      - '3002:3000'
    restart: always

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: quiooo/dominik-schwaiger.ch
